@startuml
left to right direction
skinparam packageStyle rectangle


actor "Customer" as G
actor "Member" as M
actor "Staff" as S
actor "Manager" as MG

' Actor Inheritance

G <|-- M
M <|-- S
S <|-- MG

rectangle "BiblioHub Management System" {
    ' Resource Operations
    usecase "Booking Area" as UCS3
    usecase "Upgrade Area" as UC4
    usecase "Rent Or Purchase Books" as RPB1
    usecase "Search Book" as SB1
    usecase "Search Area" as SS1
    usecase "Return Book" as RB1
    usecase "Booking Book" as BB1
    usecase "Register" as RG1
    usecase "View Transaction" as VT1
    usecase "Create Promotion" as CP1

    
    ' Billing & Logic
    usecase "Checkout" as CheckoutCC1
    usecase "Process Payment" as UC6
    usecase "Notification\n(Before Timeout)" as Notification
    usecase "Calculate Promotion\n(Birthday/Double Date)" as UC7
    usecase "Calculate Penalty & Fines" as UC8
    usecase "Create Customer" as CC1
    usecase "Create Staff" as CS1
    
    ' Management
    usecase "Process Return" as UC9
    
    usecase "Generate Business Reports" as UC10


    ' Relationships
    G --> SB1
    G --> SS1
    G --> RB1
    G --> RG1
    G --> CheckoutCC1
    G --> UC4
    G --> CC1
    G --> VT1
    M --> BB1
    
    ' Extend & Include
    RG1 ..> CC1 : <<include>>
    BB1 ..> SB1 : <<include>>
    UC6 ..> UC7 : <<include>>
    UC6 ..> UC8 : <<include>>
    RPB1 <.. UC6 : <<include>>
    UCS3 <.. UC6 : <<include>>
    UCS3 <.. Notification : <<include>>
    RPB1 <.. Notification : <<include>>
    RB1 <.. UC6 : <<extend>>
    SB1 <..  RPB1 : <<include>>
    SS1 <.. UCS3 : <<include>>

    
    S --> UC9
    S --> CP1
    MG --> CS1
    
    MG --> UC10

}
@enduml