---
config:
  layout: elk
  theme: redux_dark
---
classDiagram
direction TB

    class ActivityType {
        <<enumeration>>
        Rent
        Purchase
    }
    class TypeBook {
        <<enumeration>>
        Manga
        Novel
        Historical
        Education
        Self_improvement
        Economic
    }
    class BookStatus {
        <<enumeration>>
        Available
        UnAvailable
        Selected
        Purchased
        Incoming
    }
    class PaymentStatus {
        <<enumeration>>
        Unpaid
        Paid
        Voied
    }
    class TransactionStatus {
        <<enumeration>>
        Requested
        Confirm
        In_Use
        Completed
        Cancelled
    }
    class BookingBookQuota {
        <<enumeration>>
        Silver
        Gold
        Platinum
    }
    class LevelMember {
        <<enumeration>>
        Silver
        Gold
        Platinum
    }
    class BirthMonth {
        <<enumeration>>
        Jan - Dec
    }

    class BiblioHubSystem {
        -List staff_list
        -List promotion_list
        -List book_stock
        -List area
        -List customer_list
        -List transaction_list
        -List notification_list
        +register()
        +login()
        +logout()
        +edit_profile()
        +change_permission()
        +add_book_stock()
        +add_staff()
        +add_promotion()
        +add_area()
        +remove_area()
        +add_strike()
        +reduce_strike()
        +notify_user()
        +upgrade_booking_area()
        +generate_utilization_report()
        +check_duplicate_account()
        +validate_input_data()
        +get_user_from_phone_number()
        +search_book()
        +search_area()
        +checkout()
    }

    %% --- User Management ---
    class Customer {
        -String __name
        -String __surname
        -String __phonenumber
        -String __email
        -List~Transaction~ __transaction
        -List~Notification~ __notification_list
        -DateTime __booking_reservation_time
        -Int __rental_quota
        -Int __strike
        -List~Book,Area~ __selected_list
        +check_eligibility()
        +check_quota()
        +select(order)
        +add_notify(notification)
        +add_transaction(transaction)
    }

    class Member {
        -LevelMember __level_member
        -BirthMonth __birth_month
        -Int __points
        -BookingBookQuota __booking_book_quota
        -Date __expiration_date
        +add_point()
    }

    class Staff {
        -Int count$
        -String __no_staff
        -String __no_branch
        +process_return(book, customer)
    }

    class Manager {
        +print_report()
    }

    class BookInfo {
        -String __name
        -BookStock __book_stock
        -String __author
        -TypeBook __category
        -Float __price
        -ActivityType __activity_type
        -List~Book~ __book
        -Date __available_date
        -String __id
        +add_copies(copies: int)
        +search_book_available()
    }

    class Book {
        -BookInfo __book_info
        -String __book_uid
        -Int __borrowed_count
        -BookStatus __book_status
        -Date __start_date
        -Date __end_date
        -Date __actual_return_date
        +calculate_end_date(how_many_days: int)
        +check_available()
        +change_status(status: BookStatus)
        +change_activity_type(activity_type: ActivityType)
    }

    class BookStock {
        -String __name
        -List~BookInfo~ __forsale_book_list
        -List~BookInfo~ __rent_book_list
        +get_book_list(activity_type: ActivityType)
        +add_book_info(book_info: BookInfo, activity_type: ActivityType)
        +remove_book(book)
        +search_book_available(bookname, activity_type)
    }

    class Area {
        -String area_id
        -String area_type
        -Float hourly_rate
        -List feature
        -Int capacity
        -List slots
        +list_timeslot()
        +get_rate_info()
    }

    class TimeSlot {
        -Area area
        -DateTime start_time
        -DateTime end_time
        -Bool is_available
        +update_slot()
    }

    class Order {
        -RentBook __rent_book
        -Purchase __purchase_book
        +calculate_subtotal()
        +confirm()
    }

    class Purchase {
        -List~Book,Area~ _order
        +calculate_subtotal()
        +confirm()
    }

    class RentBook {
        -Float __late_penalty_rate
        +get_penalty()
        +confirm()
    }

    class BookingBook {
        +confirm()
    }

    class BookingArea {
        +confirm()
    }

    class Promotion {
		<<abstract>>
        -String __promo_code
        -Float __discount_rate
        -Bool __status
        -List __used_user
        +is_eligible(customer)
        +apply_discount(price, customer)
        +payment_unsuccess(customer)
    }
    
    class BirthDate
    class DoubleDate

    class PaymentMethod {
        <<abstract>>
        +name*
        +process_payment(Amount)*
    }

    class Cash {
        -String __name
        +process_payment(Amount)
    }

    class QRCode {
        -String __name
        -String __phonenumber
        +process_payment(Amount)
    }

    class Payment {
        -Int count$
        -Customer __customer
        -String __payment_no
        -String __status
        -Order __order
        -DateTime __timestamp
        -PaymentMethod __payment_method
        -Float __base_fee
        -Float __upgrade_delta
        -Float __discount_amount
        -Float __penalty_fee
        -Float __net_amount
        +calculate_net_amount()
        +update_payment_status(status: PaymentStatus)
        +add_penalty_fee(penalty_fee)
    }

    class Transaction {
        -Customer __customer
        -Staff __staff
        -DateTime __start_date_time
        -DateTime __end_date_time
        -String __status
        -Payment __payment
        -List __audit_logs_list
        +update_status(status: TransactionStatus)
        +add_audit_log(log)
        +sync_payment_with_activity(rentbook: RentBook)
    }

    class Notification {
        -Int count$
        -Customer __customer
        -String __message
        -String __uid
    }

    BiblioHubSystem "0..*" <-- "1" BookingArea
    BiblioHubSystem "1" o-- "1..*" Staff
    BiblioHubSystem "1" o-- "1..*" Area
    BiblioHubSystem "1" o-- "0..*" Customer
    BiblioHubSystem "1" o-- "0..*" Transaction
    BiblioHubSystem "1" o-- "0..*" BirthDate
    BiblioHubSystem "1" o-- "0..*" DoubleDate
    BiblioHubSystem "1" o-- "1..*" BookStock
    BiblioHubSystem "1" o-- "0..*" Notification

    Customer <|-- Member
    Member <|-- Staff
    Staff <|-- Manager
    
    Purchase <|-- RentBook
    Purchase <|-- BookingBook
    Purchase <|-- BookingArea

    Transaction "1" --> "1" Staff
    Payment "1" <-- "1" Transaction
    BookingArea "1" o-- "1..*" TimeSlot
    
    Order "1" *-- "1" Purchase
    Order "1" *-- "1" RentBook
    Order "1" *-- "0..1" BookingBook
    Order "1" *-- "0..1" BookingArea
    
    Payment "1" *-- "1" Order
	Payment "1" o-- "1" PaymentMethod
    BookInfo "1" *-- "0..*" Book
    BookStock "1" o-- "0..*" BookInfo

	BirthDate "1" --|> Promotion
	DoubleDate "1" --|> Promotion
    
    PaymentMethod <|-- Cash
    PaymentMethod <|-- QRCode