sequenceDiagram
    autonumber
    actor NMB as NonMember
    actor MB as Member
    participant SYS as BiblioHubSystem
    participant BS as BookStock
    participant BK as Book

    loop Select Book 
        NMB ->> SYS: search_book(phonenumber,book_series)
        SYS ->> SYS: get_user_from_phone_number(phonenumber)
        SYS ->> NMB: check_eligibility()
        NMB -->> SYS: return eligibility status : bool

        alt eligibility successful
            BS -->> SYS: return bookstock [object]
            SYS ->> NMB: return bookstock
        else
            SYS --> NMB: return you not able to rent
        end

    end

    loop select action type
        NMB ->> BK: change_activity_type
        
        opt rent action type
            BK ->> NMB: check_quota()
            NMB -->> BK: return quota status [bool]

            opt due quota limit
                BK -->> NMB: error due quota limit
            end

        end


        BK -->> NMB: change_activity_type successful
    end

    NMB ->> SYS: checkout(select[List])
    loop all in select
        SYS ->> BK: get_activity_type()
        BK -->> SYS: return activity_type [String]
        opt is RentBook
            create participant RB as RentBook
            SYS ->> RB: create(rental_date,due_date)
            RB -->> SYS: return RentBook object [object]
            create participant PS as Payment
            SYS ->> PS: create(order)
            PS -->> SYS: return payment object [object]

            create participant TS as Transaction
            SYS ->> TS: create(user,staff,start_date_time,end_date_time,status,payment)
            TS -->> SYS: return transaction object [object]

        end
        
    end

    SYS ->> PS: payment_method()
    PS -->> SYS: return successful

    alt Payment successful
        SYS ->> TS: update_status()
        TS -->> SYS: return successful

        loop All Book
            SYS ->> BK: change_status("Not Available")
            BK -->> SYS: change_status successful
        end

        SYS ->> SYS: notify_user()
        create participant Notify as Notification
        SYS ->> Notify: create(message,target_user)
        Notify -->> SYS: return Notification [object]
        SYS ->> Notify: send_message()
        Notify -->> SYS: return Notification status [object]

        SYS ->> NMB: add_transaction(Transaction[object])
        NMB -->> SYS: return add_transaction status[bool]

        SYS ->> NMB: add notify()
        NMB -->> SYS: return notify successful

        opt is Member
            SYS ->> MB: add_point()
        end
        SYS -->> NMB: return checkout successful

    else
        SYS -->> NMB: return checkout unsuccessful
    end


