sequenceDiagram
    autonumber
    actor NMB as NonMember
    actor MB as Member
    participant SYS as BiblioHubSystem
    participant BS as BookStock
    participant BI as BookInfo
    participant BK as Book

    loop Search Book 
        NMB ->> SYS: search_book(phonenumber,book_series)
        activate SYS
        activate NMB
        SYS ->> SYS: get_user_from_phone_number(phonenumber)
        SYS ->> NMB: check_eligibility()
        NMB -->> SYS: return eligibility status : bool

        alt eligibility successful
            SYS ->> BS: get_name()
            activate BS
            BS -->> SYS: return name [String]
            deactivate BS
            SYS -->> NMB: return bookstock [object]
        else eligibility unsuccessful
            SYS -->> NMB: Don't come in to my place, Go away and don't comeback
        end

        deactivate SYS
    end

    loop Select Book
        NMB ->> SYS: select_book(phonenumber,book_id,start_date,num_days)
        activate SYS
        SYS ->> SYS: get_user_from_phone_number(phonenumber)
        SYS ->> NMB: check_quota()
        NMB -->> SYS: return quota status [bool]
        deactivate NMB
        SYS ->> SYS: get_book(series,book_name,activity_type)
        SYS ->> BS: search_book_available(bookname,activity_type)
        activate BS
        BS ->> BI: search_book_available()
        activate BI
        BI -->> BS: return book_info [object]
        deactivate BI
        BS -->> SYS: return book [object]
        deactivate BS
        SYS ->> NMB: select(book)
        activate NMB
        NMB -->> SYS: return select successful
        SYS -->> NMB: return select successful
        deactivate SYS
    end

    NMB ->> SYS: checkout(customer,staff,payment_method)
    deactivate NMB
    activate SYS
    create participant Order as Order
    SYS ->> Order: create()
    activate Order
    Order -->> SYS: return order object [object]
    deactivate Order

    SYS ->> NMB: get_selected_list()
    NMB -->> SYS: return selected_list [list]

    alt is RentBook
        create participant RB as RentBook
        SYS ->> RB: create(book_rent_list)
        activate RB
        RB -->> SYS: return RentBook object [object]
        deactivate RB
        SYS ->> Order: set_rent_book(RentBook[object])
        activate Order
        Order -->> SYS: return set_rent_book successful
        deactivate Order
    else is PurchaseBook
        create participant PB as PurchaseBook
        SYS ->> PB: create(book_purchase_list)
        activate PB
        PB -->> SYS: return PurchaseBook object [object]
        deactivate PB
        SYS ->> Order: set_purchase_book(PurchaseBook[object])
        activate Order
        Order -->> SYS: return set_purchase_book successful
        deactivate Order
    end

    create participant PMM as PaymentMethod
    SYS ->> PMM: create(payment_method)
    activate PMM
    PMM -->> SYS: return PaymentMethod object [object]
    deactivate PMM

    create participant PM as Payment
    SYS ->> PM: process_payment(customer,order,payment_method)
    activate PM
    PM -->> SYS: return payment status [bool]
    deactivate PM
    create participant TS as Transaction
    SYS ->> TS: create(customer,staff,payment,datetime.now(),datetime.now())
    activate TS
    TS -->> SYS: return Transaction object [object]

    SYS ->> TS: add_audit_log("Transaction requested")
    TS -->> SYS: return add_audit_log successful
    deactivate TS

    SYS ->> PM: calculate_net_amount()
    activate PM
    PM -->> SYS: return net amount [float]
    deactivate PM

    SYS ->> PMM: process_payment()
    activate PMM
    PMM -->> SYS: return payment status [bool]
    deactivate PMM

    alt Payment successful
        SYS ->> PM: update_payment_status("Paid")
        activate PM
        PM -->> SYS: return update_payment_status successful
        deactivate PM
        SYS ->> TS: update_transaction_status("Confirmed")
        activate TS
        TS -->> SYS: return successful
        SYS ->> TS: add_audit_log("transaction completed")
        TS -->> SYS: return add_audit_log successful
        deactivate TS

        SYS ->> Order: confirm()
        activate Order
        Order -->> SYS: return confirm successful
        deactivate Order

        SYS ->> SYS: notify_user()
        create participant Notify as Notification
        SYS ->> Notify: create(message,target_user)
        activate Notify
        Notify -->> SYS: return Notification [object]
        SYS ->> Notify: send_message()
        Notify -->> SYS: return Notification status [object]
        deactivate Notify

        SYS ->> NMB: add_transaction(Transaction[object])
        activate NMB
        NMB -->> SYS: return add_transaction status[bool]

        SYS ->> NMB: add notify()
        NMB -->> SYS: return notify successful

        opt is Member
            SYS ->> MB: add_point()
            activate MB
            MB -->> SYS: return add_point successful
            deactivate MB
        end
        SYS -->> NMB: return checkout successful

    else
        SYS -->> NMB: return checkout unsuccessful
        deactivate NMB
        deactivate SYS
    end


