sequenceDiagram
    autonumber
    actor Customer
    participant SYS as BiblioHubSystem
    participant User
    participant BS as BookStock
    participant BI as BookInfo
    participant BK as Book
    
    %% Select Book

    Customer ->>+ SYS: select_book(phonenumber,item_id,num_days)
        
    SYS ->> SYS: get_user_from_phone_number(phonenumber)
    NOTE over SYS: get_user_from_phone_number method
    SYS ->> SYS: validate_phonenumber(phonenumber)

    opt Invalid Phone Number Format
        SYS -->> Customer: return error message "Invalid phone number format"
    end

    alt Invalid Phone Number
        SYS -->> Customer: return error message "Invalid phone number"
    else Valid Phone Number
        loop customer in customer_list
            SYS ->>+ User: get_phone_number():
            User -->>- SYS: return phone_number

            alt phone_number found
                NOTE right of SYS: return customer object
            else phone_number not found
                NOTE right of SYS: return error message "Phone number not found"
            end
        end
        NOTE over SYS: end of get_user_from_phone_number method
    end

    SYS ->> SYS: check_type_from_id(item_id)

    NOTE over SYS: check_type_from_id method
    alt Invalid ID Format
        SYS -->> Customer: return error message "Invalid ID format"
    else Valid ID Format
        alt ID starts with "BK"
            NOTE left of SYS: return "Book"
        else ID starts with "AR"
            NOTE left of SYS: return "Area"
        else Invalid ID Prefix
            SYS -->> Customer: return error message "Invalid ID format"
        end
    end

    NOTE over SYS: end of check_type_from_id method

    SYS ->> SYS: get_data_from_id(item_id)
    NOTE over SYS: get_data_from_id method

    alt Type of Item is "Book"
        NOTE left of SYS: return activity_type, series, book_name, author
    else Type of Item is "Area"
        NOTE left of SYS: return area information (if applicable)
    else Invalid Type of Item
        SYS -->> Customer: return error message "Invalid ID format"
    end

    NOTE over SYS: end of get_data_from_id method

    alt Activity Type is Rent
        SYS ->>+ User: check_quota()
        User -->>- SYS: return quota status [bool]

        opt Quota Not Available
            SYS -->> Customer: return error message "Quota not available"
        end
    end

    SYS ->> SYS: get_book_info(series,book_name,author,activity_type)
    NOTE over SYS: get_book_info method
    
    loop bookstock in bookstock_list
        SYS ->>+ BS: get_book_series()
        BS -->>- SYS: return book_series [string]
        
        opt series matches
            SYS ->>+ BS: get_book_info_by_name(book_name,author,activity_type)
            opt activity_type match
                loop book_info in book_info with match activity_type
                    BS ->>+ BI: get_book_info_name()
                    BI -->>- BS: book_info_name()

                    opt book_info_name match
                        BS -->>- SYS: return Book Info
                    end
                end
            end
        

            alt book_info found
                NOTE right of SYS: return book_info object
            else book_info not found
                NOTE right of SYS: return error message "Book Info not found"
            end
        end
    end

    NOTE over SYS: end of get_book method

    SYS ->>+ User: select(book_info,num_days)
    create participant BookOrder
    User ->>+ BookOrder: create(order,num_days)
    BookOrder -->>- User: return BookOrder [object]
    User -->>- SYS: return order
    SYS -->>- Customer: return select successful

    


