sequenceDiagram
    autonumber
    actor Customer as Member / NonMember
    participant System as BiblioHubSystem
    participant Customers as Customer
    
    participant AreaObj as Area
    participant Slot as TimeSlot    

    %% Select Area and Slot
    Customer->>System: select_area(phonenumber,area_id,List[slot_ids])
    activate System
    System->>System: get_user_from_phone_number(phonenumber)
    
    System->>Customers: check_quota(phonenumber)
    activate Customers
    
    alt โควต้าผ่าน (Success Case)
        Customers-->>System: return quota[True]
        deactivate Customers
        System-->>Customer: return {"status": "Success", "message": f"นำสล็อต {slot_names} ของ {area_id.value} ใส่ตะกร้าแล้ว"}
    else สิทธิ์ไม่ผ่าน หรือ มีการจองซ้อน (Failure Case)
        System-->>Customer: return {"error": f"โควต้าเต็ม! คุณจองได้อีก {customer.get_area_quota() - customer.booking_reservation_time} ชม."}
    end
    deactivate System

    %% Checkout Area
    Customer->>System: checkout_area(phonenumber,payment_method)
    activate System
    loop เช็คว่ามี Area ใน attribute selected_list ในตัว customer
        alt มี area ใน customer (Success Case)
            create participant BArea as BookingArea
            System->>BArea: create_booking_area(all_slots, the_room)
            activate BArea
            BArea -->>System: return booking_area_obj
            deactivate BArea
            
            System->>System: checkout(customer, Staff(), [booking_order], payment_method)
            System-->>Customer: return ทำรายการสำเร็จ ชำระเงินรวมทั้งสิ้น net_amount บาท
        else ไม่มี area ใน customer (Failure Case)
            System-->>Customer: return ไม่มีรายการจองที่นั่ง
        end
    end
    deactivate System