sequenceDiagram
    autonumber
    actor US as User
    participant SYS as System
    participant CS as Customer
    participant BS as BookStock
    participant BI as BookInfo
    participant BK as Book

    Note over US, SYS: --- PURCHASE SEARCH PHASE ---
    US->>SYS: search_book(phone, series) 
    activate SYS
    
    SYS->>SYS: get_customer_by_phone(phone)
    
    loop check_eligibility in Customer
        SYS ->> CS: check_eligibility()
        activate CS
        CS -->> SYS: return bool
        deactivate CS
    end
    loop search_book
        SYS ->> SYS: search_book(book_series)
        SYS ->> BS: search_book_available(name, activity_type = "Purchase")
        activate BS
        BS ->> BI: search_book_available()
        activate BI
        loop check_available
            BI ->> BK: check_available()
            activate BK
            BK -->> BI: return status
            deactivate BK
        end
        BI -->> BS: return available_status
        deactivate BI
        BS -->> SYS: return available_book
        deactivate BS
        SYS -->> US: return bookstock[object]
    end
    deactivate SYS


    Note over US, SYS: --- SELECT BOOK PHASE ---
    loop Select Book
        US ->> SYS: select_book(phone, book_name, activity_type = "Purchase")
        activate SYS
        SYS ->> SYS: get_customer_by_phone(phone)
        SYS ->> SYS: get_bookinfo(series, name, activity_type)

        SYS ->> BS: search_bookinfo(name, activity_type = "Purchase")
        activate BS
        BS ->> BI: get_bookinfo()
        activate BI
        BI -->> BS: return bookinfo
        deactivate BI
        BS -->> SYS: return bookinfo
        deactivate BS

        SYS ->> CS: select(book)
        activate CS
        create participant BO as BookOrder
        CS ->> BO: BookOrder(BookInfo)
        activate BO
        BO -->> CS: return book_order
        deactivate BO
        CS -->> SYS: return selected_list[]
        deactivate CS
        SYS -->> US: return selected_list[]
        deactivate SYS
    end

    Note over US, SYS: --- CHECKOUT PHASE ---
    US ->> SYS: checkout_purchase(phonenumber, payment_method)
    activate SYS
    
    loop check Book attribute selected_list in customer
        alt Book in customer (Success Case)
            loop check activity_type Book
                alt activity_type is "Purchase"
                    create participant PS as Purchase
                    SYS ->> PS: create_purchase(order)
                    activate PS
                    PS -->> SYS: return Purchase Object
                    deactivate PS
                    SYS ->> SYS: checkout(customer, Staff(), [order], payment_method) 
                    SYS -->> US: return Completed. Total payment made net_amount bath
                else
                    SYS -->> US: return activity_type is "Rent"
                end
            end
        else not Book in customer (Failure Case)
            SYS -->> US: return Don't has Purchase
        end
    end
    deactivate SYS
