sequenceDiagram
    autonumber
    actor Customer as Member / NonMember
    participant Customers as Customer
    participant System as BiblioHubSystem
    participant AreaObj as Area
    participant Slot as TimeSlot    

    Customer->>System: search_area(phonenumber,area_id)
    loop check_eligibility ใน Customers
        System->>Customers: check_eligibility(phonenumber)
        Customers-->>System: return ประวัติดี
    end
    loop ค้นหา Timeslot ใน area
        System->>AreaObj: list_timeslot(area_id)
        loop  TimeSlot ใน Area ว่าว่างหรือไม่
            AreaObj->>Slot: check is_available
            Slot-->>AreaObj: return status
        end
        AreaObj-->>System: return available_slots
    end

    System-->>Customer: return {"area_id": area_id, "available_slots": available_slots}

    Customer->>System: select_area(phonenumber,area_id,List[slot_ids])
    System->>System: get_user_from_phone_number(phonenumber)
    System->>Customers: check_quota(phonenumber)
    alt โควต้าผ่าน (Success Case)
        Customers-->>System: return quota[True]
        System->>System:validate_booking_conflict(area_id)
        System-->>Customer: return {"status": "Success", "message": f"นำสล็อต {slot_names} ของ {area_id.value} ใส่ตะกร้าแล้ว"}
    else สิทธิ์ไม่ผ่าน หรือ มีการจองซ้อน (Failure Case)
        System-->>Customer: return {"error": f"โควต้าเต็ม! คุณจองได้อีก {customer.get_area_quota() - customer.booking_reservation_time} ชม."}
    end
    
