sequenceDiagram
    autonumber
    actor S as BiblioHubSystem
    participant SYS as System
    participant TS as Transaction
    participant BA as BookingArea
    participant TM as TimeSlot
    participant RB as RentBook
    participant B as Book
    participant BB as BookingBook

    S->>SYS: check_upcoming_deadlines(current_datetime)
    activate SYS

    SYS->>SYS: process_notifications(current_datetime)

    loop each Transaction in __transaction_list
        SYS->>TS: get_customer()
        activate TS
        TS-->>SYS: customer_obj
        deactivate TS

        Note over SYS: pending_notifies = [] (List of String Messages)

        opt Object is BookingArea (TimeSlot)
            SYS->>BA: get_area_order()
            activate BA
            BA-->>SYS: List<TimeSlot>
            deactivate BA

            loop each Slot
                SYS->>TM: get_slot_times()
                activate TM
                TM-->>SYS: return start_time, end_time
                deactivate TM

                SYS->>SYS: should_notify(current_time, item : TimeSlot, customer_name)
                Note right of SYS: if match, append "Area_Message" to pending_notifies
            end
        end

        opt Object is RentBook
            SYS->>RB: get_rent_order()
            activate RB
            RB-->>SYS: List<Book>
            deactivate RB

            loop each Book
                SYS->>B: get_rental_dates()
                activate B
                B-->>SYS: return start_date, end_date
                deactivate B

                SYS->>SYS: should_notify(current_time, item : Book, customer_name)
                Note right of SYS: if match, append "Rent_Message" to pending_notifies
            end
        end

        opt Object is BookingBook
            SYS->>BB: get_booking_book_order()
            activate BB
            BB-->>SYS: return booking_book_obj

            SYS->>BB: get_pickup_deadline()
            BB-->>SYS: return pickup_deadline
            deactivate BB

            SYS->>SYS: should_notify(current_time, item : BookingBook, customer_name)
            Note right of SYS: if match, append "Booking_Message" to pending_notifies
        end

        loop each message in pending_notifies
            SYS->>SYS: notify_user(customer_obj, message)
            Note right of SYS: Save Notification to List
        end

    end

    SYS-->>S: status("Notification checked")
    deactivate SYS